# Configuration file for custom user settings
set(CMAKE_FIND_ROOT_PATH "D:\\GNU Arm Embedded Toolchain\\10 2021.10\\bin")

if(DEFINED RASC_EXE_PATH)
    message("Using RASC_EXE_PATH defined via CLI -D: ${RASC_EXE_PATH}")
elseif(DEFINED ENV{RASC_EXE_PATH})
    set(RASC_EXE_PATH $ENV{RASC_EXE_PATH})
    message("Using RASC_EXE_PATH defined in environment: ${RASC_EXE_PATH}")
else ()
    set(RASC_EXE_PATH "D:/Renesas/RA/sc_v2024-07_fsp_v5.5.0/eclipse/rasc.exe")
    message("Using RASC_EXE_PATH generated by RASC: ${RASC_EXE_PATH}")
endif()
