# This file was automatically generated by RASC

# This CMake script executes RASC to regenerate project files from the current
# device configuration (as specified in configuration.xml). Typically this
# is executed as a pre-build step when the device configuration has changed:
#
#  cmake -P /path/to/prebuild.cmake
#
# Changing the device configuration currently also regenerates the content of
# the cmake files so this needs to run as a separate step.
#

# The directory containing this script; used to locate the configuration.xml
# and Config.cmake irrespective of the caller directory
set(SCRIPT_DIR ${CMAKE_SCRIPT_MODE_FILE}/..)
set(RASC_CONFIG_FILE ${SCRIPT_DIR}/../configuration.xml)

include(${SCRIPT_DIR}/../Config.cmake)

execute_process(COMMAND ${RASC_EXE_PATH} -nosplash --launcher.suppressErrors --generate --devicefamily ra --compiler GCC --toolchainversion ${CMAKE_C_COMPILER_VERSION} ${RASC_CONFIG_FILE}
    RESULT_VARIABLE RASC_EXIT_CODE)

if(NOT RASC_EXIT_CODE EQUAL "0")
    message(FATAL_ERROR "Failed to run RASC generate command")
endif()
